package uncheckedExce;

public class TryCatchBl {
	public static void main(String[] args) {
		int a[] = new int[5];

		try {
			int result = 5 / 0;

		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
			System.out.println(e.getStackTrace());
			System.out.println(e.getCause());
			// TODO: handle exception
		}

		// Note- the code execute line by line so that why exception also check line by
		// line

		System.out.println("execute line by line");
//		System.out.println(a[6]); //getting exception ArrayIndexOutOfBound
		try {
			System.out.println(a[6]);
			// int result=5/0;

		} catch (ArrayIndexOutOfBoundsException e) {

			System.out.println("try to access out of bound element");
			// TODO: handle exception
		}

		System.out.println("terminate at the end");
	}
}
